### ISSUE TITLE
Setup code/framework

### ISSUE THREAD

**Issue by ngocduy1902** [ngocduy1902/CCMTPTPM-Nhom06#6]
## TODO

- [ ] #10
- [ ] #11
- [ ] #12

**Comment by ngocduy1902** [comment]
## TODO

- [ ] So sánh các framework để viết backend và lựa chọn một trong số những framework đó
- [ ] So sánh các framework để viết frontend và lựa chọn một trong số những framework đó
- [ ] Dùng một framework thử tạo một frontend đơn giản
